### ISSUE TITLE
Giving a user clear information on each  unauthorized attempt where its not given in the frontend 

### ISSUE THREAD

**Issue by divinecharlotte** [d-rec/drec-origin#413]
Subticket of https://github.com/d-rec/drec-ui/issues/149

### **Objective:**
Giving a user clear information everywhere an  UnauthorizedException() is thrown.

### **Description:**
- Check everywhere  UnauthorizedException() is thrown .
- Everywhere UnauthorizedException() is thrown send a message with information explaining why it’s un-authorized.
- If it's error 403: Say something "You don't have the right permission to access this resource"
- if it's error 401: We should direct to the login page

### **Acceptance Criteria:**
- The project runs as expected with clear information wherever UnauthorizedException() is thrown.
- UnauthorizedException() is thrown as expected.

**Comment by Kingcedru** [comment]
- Change the title name there are some typos
